name: Deploy Infrastructure

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # Required for requesting the JWT OIDC token
  contents: read    # Required for actions/checkout

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }} # e.g. arn of role/fanvault-github-actions-role
          aws-region: us-east-1
          audience: sts.amazonaws.com

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan & Apply
        run: |
          terraform plan
          terraform apply -auto-approve