aws_region   = "us-east-1"
project_name = "fanvault"
environment  = "dev"
github_repo  = "Fanvault-CloudOps/Fanvault-v3-App"
jwt_secret         = "REPLACE_WITH_32_PLUS_CHAR_RANDOM_STRING"
jwt_refresh_secret = "REPLACE_WITH_DIFFERENT_32_PLUS_CHAR_RANDOM_STRING"